config_filename: "default_rnn.yaml"
description: "copying memory task"

project_name: "wa_copy"
ex_name: "wa_adam_5"

# model specific details

hidden_size: 100


# optimization specific details

# Valid optimizer names: Adadelta, Adagrad, Adam, RMSprop, TA_RMSprop, SGD
optim_name: "RMSprop"
lr: 1.0e-2
momentum: 0
alpha: 0.99
eps: 1.0e-8
beta1: 0.9
beta2: 0.999
max_steps: 100
beta1: 0.9
beta2: 0.999
gamma: 0.9

max_steps: 200
rseed:  5

# task specific details
task: "copying_memory"
batch_size: 500
seed: 5
time_lag_min: 5
time_lag_max: 5
seq_len: 2
num_noise_digits: 1
num_digits: 8

# saving details
use_tflogger: True
save_every_n: 10000000
inter_saving: False
