config_filename: "default_rnn.yaml"
description: "copying memory task"

project_name: "pmnist_wa"
ex_name: "rmsprop_janet"

# model specific details

hidden_size: 100
input_size: 1
output_size: 10


# optimization specific details

# Valid optimizer names: Adadelta, Adagrad, Adam, RMSprop, TA_RMSprop, SGD
optim_name: "torch_RMSprop"
lr: 1.0e-2
momentum: 0
alpha: 0.99
eps: 1.0e-8
beta1: 0.9
beta2: 0.999
max_steps: 100
beta1: 0.9
beta2: 0.999
gamma: 0.9

max_steps: 200000
rseed:  5
device: 'cuda'

# task specific details
task: "pmnist"
batch_size: 100
seed: 5
time_lag_min: 5
time_lag_max: 5
seq_len: 2
num_noise_digits: 1
num_digits: 8

# saving details
use_tflogger: True
save_every_n: 10000000
inter_saving: False
